# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from scipy.integrate import solve_ivp
from time import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap,QIntValidator,QFont,QTransform,QDoubleValidator
from PyQt5.QtCore import QRect,Qt,QMetaObject,QCoreApplication,QTimer
from PyQt5.QtWidgets import QWidget,QTabWidget,QLabel,QSlider,QPushButton,QLineEdit,QGridLayout,QMenuBar,QStatusBar,QApplication,QMainWindow,QFrame,QCheckBox
from pyqtgraph import PlotWidget,mkPen
from numpy import zeros,append,array,linspace
from inputparam import InputParam as Param
from constants import Constants as Const
from reactivity import Reactivity as React
from parameter_s import parameter_s as par_s

z1z2_initiate_value = -100
zs_initiate_value = 0
ramp_speed_innate_value = 0.3

class Ui_MainWindow(object):
    def __init__(self):
        #initiate
        self.rho = Param.rho
        self.Q = Param.power #Inisialisasi Daya Awal (kW)
        self.T = Param.t_reactor #Suhu Reaktor (K) INISIALISASI
        self.h = Const.t_interval
        self.rhoin = Param.rho
        self.Y0 = zeros(8)
        self.Y0[0] = self.Q # Nilai daya pada kolom ke-1 q
        self.Y0[1:7] = Const.precursor_groups
        self.Y0[7] = self.T # Nilai suhu inisial reaktor """
        self.i = 1
        self.OnRampz1=0
        self.OnRampz2=0
        self.OnRampzs=0
        self.v1_end=0
        self.v2_end=0
        self.vs_end=0
        self.dvz1=0
        self.dvz2=0
        self.dvzs=0
        self.DoubleSlider=0
        self.maximize_plot=None
        self.z1 = z1z2_initiate_value
        self.z2 = z1z2_initiate_value
        self.zs = zs_initiate_value
        self.ratio = 1000 
        self.Q_mode = 0 #Mode Grafik (Linear/Logaritmik)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")

        #Instruksi Page
        self.InstruksiPage = QtWidgets.QWidget()
        self.InstruksiPage.setObjectName("InstruksiPage")
        self.KembaliButton_3 = QtWidgets.QPushButton(self.InstruksiPage)
        self.KembaliButton_3.setGeometry(QtCore.QRect(10, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.KembaliButton_3.setFont(font)
        self.KembaliButton_3.setObjectName("KembaliButton_3")

        self.SimulasiLabel_3 = QtWidgets.QLabel(self.InstruksiPage)
        self.SimulasiLabel_3.setGeometry(QtCore.QRect(110, 20, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SimulasiLabel_3.setFont(font)
        self.SimulasiLabel_3.setObjectName("SimulasiLabel_3")

        self.InstruksiScroll = QtWidgets.QScrollArea(self.InstruksiPage)
        self.InstruksiScroll.setGeometry(QtCore.QRect(10, 130, 1240, 520))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InstruksiScroll.sizePolicy().hasHeightForWidth())
        self.InstruksiScroll.setSizePolicy(sizePolicy)
        self.InstruksiScroll.setMinimumSize(QtCore.QSize(0, 520))
        self.InstruksiScroll.setMaximumSize(QtCore.QSize(1240, 520))
        self.InstruksiScroll.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.InstruksiScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.InstruksiScroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.InstruksiScroll.setWidgetResizable(True)
        self.InstruksiScroll.setObjectName("InstruksiScroll")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -304, 1221, 822))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(20, 15, 15, 15)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)

        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)

        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)

        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)

        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)

        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setMaximumSize(QtCore.QSize(1280, 57))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")

        self.verticalLayout_2.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_2.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_2.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_2.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setWordWrap(False)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_2.addWidget(self.label_35)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.label_34)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_2.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_2.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_2.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_2.addWidget(self.label_39)

        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_2.addWidget(self.label_40)

        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_2.addWidget(self.label_41)

        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_2.addWidget(self.label_42)

        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_2.addWidget(self.label_43)

        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_2.addWidget(self.label_44)

        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_2.addWidget(self.label_45)

        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_2.addWidget(self.label_47)

        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_2.addWidget(self.label_46)

        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_2.addWidget(self.label_48)

        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_2.addWidget(self.label_49)

        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_2.addWidget(self.label_50)

        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_2.addWidget(self.label_51)

        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)

        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)

        self.InstruksiScroll.setWidget(self.scrollAreaWidgetContents)
        self.label_18 = QtWidgets.QLabel(self.InstruksiPage)
        self.label_18.setGeometry(QtCore.QRect(10, 90, 841, 41))
        self.label_18.setObjectName("label_18")

        self.stackedWidget.addWidget(self.InstruksiPage)
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.label_19 = QtWidgets.QLabel(self.HomePage)
        self.label_19.setGeometry(QtCore.QRect(30, 40, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        self.label_20 = QtWidgets.QLabel(self.HomePage)
        self.label_20.setGeometry(QtCore.QRect(30, 90, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setObjectName("label_20")

        self.SimulasiButton = QtWidgets.QPushButton(self.HomePage)
        self.SimulasiButton.setGeometry(QtCore.QRect(40, 330, 141, 41))
        self.SimulasiButton.setStyleSheet("")
        self.SimulasiButton.setObjectName("SimulasiButton")

        self.SimulasiButton.clicked.connect(self.Simulasi)
        self.TentangButton = QtWidgets.QPushButton(self.HomePage)
        self.TentangButton.setGeometry(QtCore.QRect(40, 390, 141, 41))
        self.TentangButton.setObjectName("TentangButton")

        self.TentangButton.clicked.connect(self.Tentang)
        self.InstruksiButton = QtWidgets.QPushButton(self.HomePage)
        self.InstruksiButton.setGeometry(QtCore.QRect(40, 270, 141, 41))
        self.InstruksiButton.setObjectName("InstruksiButton")

        self.InstruksiButton.clicked.connect(self.Instruksi)
        self.KeluarButton = QtWidgets.QPushButton(self.HomePage)
        self.KeluarButton.setGeometry(QtCore.QRect(40, 450, 141, 41))
        self.KeluarButton.setObjectName("KeluarButton")

        self.label_11 = QtWidgets.QLabel(self.HomePage)
        self.label_11.setGeometry(QtCore.QRect(350, 190, 401, 361))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("E:\\Simulator MHRP/img/LogoUGM.png"))
        self.label_11.setObjectName("label_11")

        #Simulasi Page
        self.stackedWidget.addWidget(self.HomePage)
        self.SimulasiPage = QtWidgets.QWidget()
        self.SimulasiPage.setObjectName("SimulasiPage")
        self.SimulasiLabel = QtWidgets.QLabel(self.SimulasiPage)
        self.SimulasiLabel.setGeometry(QtCore.QRect(120, 20, 111, 41))

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SimulasiLabel.setFont(font)
        self.SimulasiLabel.setObjectName("SimulasiLabel")
        self.KembaliButton = QtWidgets.QPushButton(self.SimulasiPage)

        self.KembaliButton.setGeometry(QtCore.QRect(20, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.KembaliButton.setFont(font)
        self.KembaliButton.setObjectName("KembaliButton")

        self.frameZ1 = QtWidgets.QFrame(self.SimulasiPage)
        self.frameZ1.setGeometry(QtCore.QRect(20, 70, 411, 241))
        self.frameZ1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameZ1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameZ1.setObjectName("frameZ1")

        self.label = QtWidgets.QLabel(self.frameZ1)
        self.label.setGeometry(QtCore.QRect(380, 90, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.Z1StepButton_1 = QtWidgets.QPushButton(self.frameZ1)
        self.Z1StepButton_1.setGeometry(QtCore.QRect(20, 200, 41, 23))
        self.Z1StepButton_1.setObjectName("Z1StepButton_1")
        self.Z1StepButton_1.clicked.connect(lambda x:self.StepRampButton(1,-100))

        self.Z1StepButton_2 = QtWidgets.QPushButton(self.frameZ1)
        self.Z1StepButton_2.setGeometry(QtCore.QRect(70, 200, 41, 23))
        self.Z1StepButton_2.setObjectName("Z1StepButton_2")
        self.Z1StepButton_2.clicked.connect(lambda x:self.StepRampButton(1,-51))

        self.Z1StepButton_3 = QtWidgets.QPushButton(self.frameZ1)
        self.Z1StepButton_3.setGeometry(QtCore.QRect(120, 200, 41, 23))
        self.Z1StepButton_3.setObjectName("Z1StepButton_3")
        self.Z1StepButton_3.clicked.connect(lambda x:self.StepRampButton(1,0))

        self.label_3 = QtWidgets.QLabel(self.frameZ1)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.line = QtWidgets.QFrame(self.frameZ1)
        self.line.setGeometry(QtCore.QRect(0, 150, 431, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.horizontalSlider = QtWidgets.QSlider(self.frameZ1)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 90, 321, 22))
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(-100*self.ratio)
        self.horizontalSlider.setMaximum(0)
        self.horizontalSlider.setValue(z1z2_initiate_value*self.ratio)
        self.horizontalSlider.valueChanged.connect(self.valuechange1)

        self.Z1Label = QtWidgets.QLabel(self.frameZ1)
        self.Z1Label.setGeometry(QtCore.QRect(20, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Z1Label.setFont(font)
        self.Z1Label.setObjectName("Z1Label")

        self.line_2 = QtWidgets.QFrame(self.frameZ1)
        self.line_2.setGeometry(QtCore.QRect(173, 160, 20, 81))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.label_5 = QtWidgets.QLabel(self.frameZ1)
        self.label_5.setGeometry(QtCore.QRect(20, 165, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.Z1RampButton_1 = QtWidgets.QPushButton(self.frameZ1)
        self.Z1RampButton_1.setGeometry(QtCore.QRect(200, 200, 41, 23))
        self.Z1RampButton_1.setObjectName("Z1RampButton_1")
        self.Z1RampButton_1.clicked.connect(lambda x:self.Rampfunction(2,-100))

        self.Z1RampButton_2 = QtWidgets.QPushButton(self.frameZ1)
        self.Z1RampButton_2.setGeometry(QtCore.QRect(250, 200, 41, 23))
        self.Z1RampButton_2.setObjectName("Z1RampButton_2")
        self.Z1RampButton_2.clicked.connect(lambda x:self.Rampfunction(2,-51))

        self.Z1RampButton_3 = QtWidgets.QPushButton(self.frameZ1)
        self.Z1RampButton_3.setGeometry(QtCore.QRect(300, 200, 41, 23))
        self.Z1RampButton_3.setObjectName("Z1RampButton_3")
        self.Z1RampButton_3.clicked.connect(lambda x:self.Rampfunction(2,0))

        self.RampLabel = QtWidgets.QLabel(self.frameZ1)
        self.RampLabel.setGeometry(QtCore.QRect(200, 165, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.RampLabel.setFont(font)
        self.RampLabel.setObjectName("RampLabel")

        self.Z1RampEdit = QtWidgets.QLineEdit(self.frameZ1)
        self.Z1RampEdit.setGeometry(QtCore.QRect(360, 200, 41, 23))
        self.Z1RampEdit.setValidator(QIntValidator())
        self.Z1RampEdit.setAlignment(Qt.AlignCenter)
        self.Z1RampEdit.setObjectName("Z1RampEdit")
        self.Z1RampEdit.editingFinished.connect(lambda:self.Rampfunction(2,int(self.input_ramp_z1.text())) if int(self.input_ramp_z1.text())<=0 and int(self.input_ramp_z1.text())>=-100 else self.stop_ramp(2))

        self.label_slider_1 = QtWidgets.QLabel(self.frameZ1)
        self.label_slider_1.setGeometry(QtCore.QRect(180, 110, 80, 20))
        self.label_slider_1.setText(str(z1z2_initiate_value))
        self.label_slider_1.setAlignment(Qt.AlignCenter)
        self.label_slider_1.setObjectName("label_slider_1")
        
        self.frameZ1_2 = QtWidgets.QFrame(self.SimulasiPage)
        self.frameZ1_2.setGeometry(QtCore.QRect(440, 70, 411, 241))
        self.frameZ1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameZ1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameZ1_2.setObjectName("frameZ1_2")

        self.label_2 = QtWidgets.QLabel(self.frameZ1_2)
        self.label_2.setGeometry(QtCore.QRect(380, 90, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.Z2StepButton_1 = QtWidgets.QPushButton(self.frameZ1_2)
        self.Z2StepButton_1.setGeometry(QtCore.QRect(20, 200, 41, 23))
        self.Z2StepButton_1.setObjectName("Z2StepButton_1")
        self.Z2StepButton_1.clicked.connect(lambda x:self.StepRampButton(3,-100))

        self.Z2StepButton_2 = QtWidgets.QPushButton(self.frameZ1_2)
        self.Z2StepButton_2.setGeometry(QtCore.QRect(70, 200, 41, 23))
        self.Z2StepButton_2.setObjectName("Z2StepButton_2")
        self.Z2StepButton_2.clicked.connect(lambda x:self.StepRampButton(3,-51))

        self.Z2StepButton_3 = QtWidgets.QPushButton(self.frameZ1_2)
        self.Z2StepButton_3.setGeometry(QtCore.QRect(120, 200, 41, 23))
        self.Z2StepButton_3.setObjectName("Z2StepButton_3")
        self.Z2StepButton_3.clicked.connect(lambda x:self.StepRampButton(3,0))

        self.label_4 = QtWidgets.QLabel(self.frameZ1_2)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.line_3 = QtWidgets.QFrame(self.frameZ1_2)
        self.line_3.setGeometry(QtCore.QRect(0, 150, 431, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.horizontalSlider_2 = QtWidgets.QSlider(self.frameZ1_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(50, 90, 321, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTracking(True)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setMinimum(-100*self.ratio)
        self.horizontalSlider_2.setMaximum(0)
        self.horizontalSlider_2.setValue(z1z2_initiate_value*self.ratio)
        self.horizontalSlider_2.valueChanged.connect(self.valuechange2)

        self.Z1Label_2 = QtWidgets.QLabel(self.frameZ1_2)
        self.Z1Label_2.setGeometry(QtCore.QRect(20, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Z1Label_2.setFont(font)
        self.Z1Label_2.setObjectName("Z1Label_2")

        self.line_4 = QtWidgets.QFrame(self.frameZ1_2)
        self.line_4.setGeometry(QtCore.QRect(173, 160, 20, 81))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.label_6 = QtWidgets.QLabel(self.frameZ1_2)
        self.label_6.setGeometry(QtCore.QRect(20, 165, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.Z2RampButton_1 = QtWidgets.QPushButton(self.frameZ1_2)
        self.Z2RampButton_1.setGeometry(QtCore.QRect(200, 200, 41, 23))
        self.Z2RampButton_1.setObjectName("Z2RampButton_1")
        self.Z2RampButton_1.clicked.connect(lambda x:self.Rampfunction(4,0))

        self.Z2RampButton_2 = QtWidgets.QPushButton(self.frameZ1_2)
        self.Z2RampButton_2.setGeometry(QtCore.QRect(250, 200, 41, 23))
        self.Z2RampButton_2.setObjectName("Z2RampButton_2")
        self.Z2RampButton_2.clicked.connect(lambda x:self.Rampfunction(4,-51))

        self.Z2RampButton_3 = QtWidgets.QPushButton(self.frameZ1_2)
        self.Z2RampButton_3.setGeometry(QtCore.QRect(300, 200, 41, 23))
        self.Z2RampButton_3.setObjectName("Z2RampButton_3")
        self.Z2RampButton_3.clicked.connect(lambda x:self.Rampfunction(4,0))

        self.RampLabel_2 = QtWidgets.QLabel(self.frameZ1_2)
        self.RampLabel_2.setGeometry(QtCore.QRect(200, 165, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.RampLabel_2.setFont(font)
        self.RampLabel_2.setObjectName("RampLabel_2")

        self.Z2RampEdit = QtWidgets.QLineEdit(self.frameZ1_2)
        self.Z2RampEdit.setGeometry(QtCore.QRect(360, 200, 41, 23))
        self.Z2RampEdit.setAlignment(Qt.AlignCenter)
        self.Z2RampEdit.setValidator(QIntValidator())
        self.Z2RampEdit.setObjectName("Z2RampEdit")
        self.Z2RampEdit.editingFinished.connect(lambda:self.Rampfunction(4,int(self.input_ramp_z2.text())) if int(self.input_ramp_z2.text())<=0 and int(self.input_ramp_z2.text())>=-100 else self.stop_ramp(4))

        self.label_slider_2 = QtWidgets.QLabel(self.frameZ1_2)
        self.label_slider_2.setGeometry(QtCore.QRect(180, 110, 80, 20))
        self.label_slider_2.setText(str(z1z2_initiate_value))
        self.label_slider_2.setAlignment(Qt.AlignCenter)
        self.label_slider_2.setObjectName("label_slider_2")

        self.frameZ1_3 = QtWidgets.QFrame(self.SimulasiPage)
        self.frameZ1_3.setGeometry(QtCore.QRect(860, 70, 411, 241))
        self.frameZ1_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameZ1_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameZ1_3.setObjectName("frameZ1_3")

        self.label_7 = QtWidgets.QLabel(self.frameZ1_3)
        self.label_7.setGeometry(QtCore.QRect(380, 90, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.ZsStepButton_1 = QtWidgets.QPushButton(self.frameZ1_3)
        self.ZsStepButton_1.setGeometry(QtCore.QRect(20, 200, 41, 23))
        self.ZsStepButton_1.setObjectName("ZsStepButton_1")
        self.ZsStepButton_1.clicked.connect(lambda x:self.StepRampButton(5,0))

        self.ZsStepButton_2 = QtWidgets.QPushButton(self.frameZ1_3)
        self.ZsStepButton_2.setGeometry(QtCore.QRect(70, 200, 41, 23))
        self.ZsStepButton_2.setObjectName("ZsStepButton_2")
        self.ZsStepButton_2.clicked.connect(lambda x:self.StepRampButton(5,75))

        self.ZsStepButton_3 = QtWidgets.QPushButton(self.frameZ1_3)
        self.ZsStepButton_3.setGeometry(QtCore.QRect(120, 200, 41, 23))
        self.ZsStepButton_3.setObjectName("ZsStepButton_3")
        self.ZsStepButton_3.clicked.connect(lambda x:self.StepRampButton(5,150))

        self.label_8 = QtWidgets.QLabel(self.frameZ1_3)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
       
        self.line_5 = QtWidgets.QFrame(self.frameZ1_3)
        self.line_5.setGeometry(QtCore.QRect(0, 150, 431, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.horizontalSlider_3 = QtWidgets.QSlider(self.frameZ1_3)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(50, 90, 321, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_3.setMinimum(0)
        self.horizontalSlider_3.setMaximum(150*self.ratio)
        self.horizontalSlider_3.setValue(zs_initiate_value*self.ratio)
        self.horizontalSlider_3.valueChanged.connect(self.valuechange3)


        self.Z1Label_3 = QtWidgets.QLabel(self.frameZ1_3)
        self.Z1Label_3.setGeometry(QtCore.QRect(20, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Z1Label_3.setFont(font)
        self.Z1Label_3.setObjectName("Z1Label_3")

        self.line_6 = QtWidgets.QFrame(self.frameZ1_3)
        self.line_6.setGeometry(QtCore.QRect(173, 160, 20, 81))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.label_9 = QtWidgets.QLabel(self.frameZ1_3)
        self.label_9.setGeometry(QtCore.QRect(20, 165, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.ZsRampButton_1 = QtWidgets.QPushButton(self.frameZ1_3)
        self.ZsRampButton_1.setGeometry(QtCore.QRect(200, 200, 41, 23))
        self.ZsRampButton_1.setObjectName("ZsRampButton_1")
        self.ZsRampButton_1.clicked.connect(lambda x:self.Rampfunction(6,0))

        self.ZsRampButton_2 = QtWidgets.QPushButton(self.frameZ1_3)
        self.ZsRampButton_2.setGeometry(QtCore.QRect(250, 200, 41, 23))
        self.ZsRampButton_2.setObjectName("ZsRampButton_2")
        self.ZsRampButton_2.clicked.connect(lambda x:self.Rampfunction(6,75))

        self.ZsRampButton_3 = QtWidgets.QPushButton(self.frameZ1_3)
        self.ZsRampButton_3.setGeometry(QtCore.QRect(300, 200, 41, 23))
        self.ZsRampButton_3.setObjectName("ZsRampButton_3")
        self.ZsRampButton_3.clicked.connect(lambda x:self.Rampfunction(6,150))

        self.RampLabel_3 = QtWidgets.QLabel(self.frameZ1_3)
        self.RampLabel_3.setGeometry(QtCore.QRect(200, 165, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.RampLabel_3.setFont(font)
        self.RampLabel_3.setObjectName("RampLabel_3")

        self.ZsRampEdit = QtWidgets.QLineEdit(self.frameZ1_3)
        self.ZsRampEdit.setGeometry(QtCore.QRect(360, 200, 41, 23))
        self.ZsRampEdit.setValidator(QIntValidator())
        self.ZsRampEdit.setAlignment(Qt.AlignCenter)
        self.ZsRampEdit.setObjectName("ZsRampEdit")
        self.ZsRampEdit.editingFinished.connect(lambda:self.Rampfunction(6,int(self.input_ramp_zs.text())) if int(self.input_ramp_zs.text())>=0 and int(self.input_ramp_zs.text())<=150 else self.stop_ramp(6))

        self.label_slider_3 = QtWidgets.QLabel(self.frameZ1_3)
        self.label_slider_3.setGeometry(QtCore.QRect(180, 110, 80, 20))
        self.label_slider_2.setText(str(zs_initiate_value))
        self.label_slider_2.setAlignment(Qt.AlignCenter)
        self.label_slider_3.setObjectName("label_slider_3")

        self.DoubleSlider = QtWidgets.QCheckBox(self.SimulasiPage)
        self.DoubleSlider.setGeometry(QtCore.QRect(310, 320, 120, 21))
        self.DoubleSlider.setObjectName("DoubleSlider")
        self.DoubleSlider.setCheckable(True)
        self.DoubleSlider.stateChanged.connect(self.DoubleSliderButton)

        self.ResetButton = QtWidgets.QPushButton(self.SimulasiPage)
        self.ResetButton.setGeometry(QtCore.QRect(1090, 322, 75, 29))
        self.ResetButton.setObjectName("ResetButton")
        self.ResetButton.clicked.connect(self.reset)

        self.MulaiButton = QtWidgets.QPushButton(self.SimulasiPage)
        self.MulaiButton.setGeometry(QtCore.QRect(1190, 322, 75, 30))
        self.MulaiButton.setObjectName("MulaiButton")
        self.MulaiButton.setCheckable(True)
        self.MulaiButton.clicked.connect(self.startStopButton)

        self.rampspeed = QtWidgets.QLineEdit(self.SimulasiPage)
        self.rampspeed.setGeometry(QtCore.QRect(120, 320, 81, 20))
        self.rampspeed.setObjectName("rampspeed")
        self.rampspeed.setText(str(ramp_speed_innate_value))
        self.rampspeed.setValidator(QDoubleValidator(0,2,3))
        self.rampspeed.setAlignment(Qt.AlignCenter)

        self.label_21 = QtWidgets.QLabel(self.SimulasiPage)
        self.label_21.setGeometry(QtCore.QRect(20, 320, 101, 21))
        self.label_21.setObjectName("label_21")
        self.stackedWidget.addWidget(self.SimulasiPage)

        #About Page
        self.AboutPage = QtWidgets.QWidget()
        self.AboutPage.setObjectName("AboutPage")
        self.SimulasiLabel_2 = QtWidgets.QLabel(self.AboutPage)
        self.SimulasiLabel_2.setGeometry(QtCore.QRect(120, 20, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SimulasiLabel_2.setFont(font)
        self.SimulasiLabel_2.setObjectName("SimulasiLabel_2")
        self.KembaliButton_2 = QtWidgets.QPushButton(self.AboutPage)
        self.KembaliButton_2.setGeometry(QtCore.QRect(20, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.KembaliButton_2.setFont(font)
        self.KembaliButton_2.setObjectName("KembaliButton_2")
        self.KembaliButton_2.clicked.connect(self.Kembali)
        self.AboutScroll = QtWidgets.QScrollArea(self.AboutPage)
        self.AboutScroll.setGeometry(QtCore.QRect(20, 100, 1231, 520))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AboutScroll.sizePolicy().hasHeightForWidth())
        self.AboutScroll.setSizePolicy(sizePolicy)
        self.AboutScroll.setMinimumSize(QtCore.QSize(0, 520))
        self.AboutScroll.setMaximumSize(QtCore.QSize(1240, 520))
        self.AboutScroll.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.AboutScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AboutScroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.AboutScroll.setWidgetResizable(True)
        self.AboutScroll.setObjectName("AboutScroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -774, 1212, 1292))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setContentsMargins(20, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")

        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")

        self.gridLayout.addWidget(self.label_64, 11, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("E:\\Simulator MHRP/img/DiagramMHRP.png"))
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 1, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 3, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_62.setText("")
        self.label_62.setWordWrap(False)
        self.label_62.setObjectName("label_62")
        self.gridLayout.addWidget(self.label_62, 10, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 2, 0, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_58.setWordWrap(True)
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 6, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.gridLayout.addWidget(self.label_59, 7, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_52.setWordWrap(True)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 0, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_65.setFont(font)
        self.label_65.setWordWrap(True)
        self.label_65.setObjectName("label_65")
        self.gridLayout.addWidget(self.label_65, 12, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_57.setMaximumSize(QtCore.QSize(1280, 57))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 5, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_60.setText("")
        self.label_60.setPixmap(QtGui.QPixmap("E:\\Simulator MHRP/img/TerasMHRP.png"))
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 8, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setWordWrap(True)
        self.label_61.setObjectName("label_61")
        self.gridLayout.addWidget(self.label_61, 9, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_56.setWordWrap(True)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 4, 0, 1, 1)
        self.AboutScroll.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.AboutPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def plotQ_mode(self):
        self.Q_mode = not self.Q_mode  #Toggle Variable between 0 and 1
        self.widget.plotItem.setLogMode(False,self.Q_mode)

        if self.Q_mode ==0:
            self.pushButton_mode_Q.setText("Logaritmic Mode")
        else:
            self.pushButton_mode_Q.setText("Linear Mode")

    def enlarge_plot(self,a,b,c):
        if self.maximize_plot == None:
            a.move(500, 10)
            a.resize(self.plotwidth,520)
            a.raise_()
            b.move(500+self.indentforlabel, 85+self.plotheight*3)
            b.raise_()
            c.move(1220, 85+self.plotheight*3)
            c.setText("Minimize")
            c.raise_()
            self.maximize_plot=a
            if a !=self.widget_plot_3 :
                self.label_nilai_R.setHidden(True)
            if a == self.widget:
                self.pushButton_mode_Q.move(1100, 85+self.plotheight*3 )

        elif self.maximize_plot==self.widget :
            a.move(500, 10)
            a.resize(  self.plotwidth,self.plotheight)
            a.raise_()
            b.move(500+self.indentforlabel, 5+self.plotheight*1)
            b.raise_()
            c.move(1220, 5+self.plotheight*1)
            c.setText("Maximize")
            self.pushButton_mode_Q.move(1100, 5+self.plotheight*1)
            c.raise_()
            self.pushButton_mode_Q.raise_()
            self.label_nilai_R.setHidden(False)
            self.maximize_plot=None
        elif self.maximize_plot==self.widget_plot_2 :
            a.move(500, 40+self.plotheight)
            a.resize(self.plotwidth,self.plotheight)
            a.raise_()
            b.move(500+self.indentforlabel, 45+self.plotheight*2)
            b.raise_()
            c.move(1220, 45+self.plotheight*2)
            c.setText("Maximize")
            c.raise_()
            self.label_nilai_R.setHidden(False)
            self.maximize_plot=None
        elif self.maximize_plot==self.widget_plot_3 :
            a.move(500, 80+self.plotheight*2)
            a.resize(self.plotwidth,self.plotheight)
            a.raise_()
            b.raise_()
            c.setText("Maximize")
            c.raise_()
            self.maximize_plot=None

    def valuechange1(self):
        value = self.horizontalSlider.value()
        self.label_slider_1.setText(str(value/self.ratio))
        self.z1 = float(value/self.ratio)
    
    def valuechange2(self):
        value = self.horizontalSlider_2.value()
        self.label_slider_2.setText(str(value/self.ratio))
        self.z2 = float(value/self.ratio)
        
    def valuechange3(self):
        value = self.horizontalSlider_3.value()
        self.label_slider_3.setText(str(value/self.ratio))
        self.zs = float(value/self.ratio)

    def valuechange_rampspeed(self,value):
        self.ramp_speed = value

    # method called by button 
    def startStopButton(self): 
            # if button is checked 
        if self.MulaiButton .isChecked():
            self.ResetButton.setEnabled(False)
            self.timer = QTimer()
            self.timer.setInterval(10)
            self.timer.timeout.connect(self.update_plot_data)
            self.timer.start()
            self.timer_on = time()
            # setting background color to light-blue 
            self.MulaiButton.setStyleSheet("background-color : #ff0033") 
            self.MulaiButton.setText("STOP")

            self.rampspeed.setReadOnly(True)
            self.rampspeed.setStyleSheet("background-color : lightgrey")
            self.valuechange_rampspeed(float(self.rampspeed.text()))
            # if it is unchecked 
        else:
            self.ResetButton.setEnabled(True)
            self.timer.stop()
                # set background color back to light-grey 
            self.pushButton.setStyleSheet("background-color : lightgrey") 
            self.pushButton.setText("START")

    def DoubleSliderButton(self): 
            # if button is checked 
        if self.DoubleSlider.isChecked():
            self.DoubleSlider=1                
                # setting background color to light-blue 
            self.DSButton.setStyleSheet("background-color : lightblue") 
            self.DSButton.setText("OFF")
            # if it is unchecked 
        else:
            self.DoubleSlider=0
                # set background color back to light-grey 
            self.DSButton.setStyleSheet("background-color : lightgrey") 
            self.DSButton.setText("ON")

    def StepRampButton(self,a,b):
        if self.DoubleSlider==1 and (int(a)==1 or int(a)==3):
            self.OnRampz1=0
            self.OnRampz2=0
            
            self.horizontalSlider.setValue(b*self.ratio)
            self.horizontalSlider_2.setValue(b*self.ratio)

        else:    
            if int(a) == 1:
                self.OnRampz1=0
                self.horizontalSlider.setValue(b*self.ratio)

            elif int(a) == 3:
                self.OnRampz2=0
                self.horizontalSlider_2.setValue(b*self.ratio)

            elif int(a) == 5:
                self.OnRampzs=0
                self.horizontalSlider_3.setValue(b*self.ratio)

                    
    def Rampfunction(self,a,b):

        #dvz = 0.00093333
        dvz = self.ramp_speed
        i_mulai = self.i
        
        if self.DoubleSlider==1 and (int(a)==2 or int(a)==4):
            self.OnRampz1=1
            helf.OnRampz2=1

            self.v1_end = b
            self.v2_end = b

            if(self.horizontalSlider.value()/self.ratio > self.v1_end):
                self.dvz1= -1*dvz
            else:
                self.dvz1= dvz

            t = (self.v1_end - self.horizontalSlider.value()/self.ratio)/self.dvz1         
            self.i_akhirz1 = i_mulai + t

            if(self.horizontalSlider_2.value()/self.ratio > self.v2_end):
                self.dvz2= -1*dvz
            else:
                self.dvz2= dvz
                
            t = (self.v2_end - self.horizontalSlider_2.value()/self.ratio)/self.dvz2
            self.i_akhirz2 = i_mulai + t

        else:
            if int(a) == 2:
                self.OnRampz1=1
                self.v1_end = b
                
                if(self.horizontalSlider.value()/self.ratio > self.v1_end):
                    self.dvz1= -1*dvz
                else:
                    self.dvz1= dvz
                
                t = (self.v1_end - self.horizontalSlider.value()/self.ratio)/self.dvz1
                self.i_akhirz1 = i_mulai + t

            if int(a) == 4:
                self.OnRampz2=1

                self.v2_end = b
                
                if(self.horizontalSlider_2.value()/self.ratio > self.v2_end):
                    self.dvz2= -1*dvz
                else:
                    self.dvz2= dvz
                
                t = (self.v2_end - self.horizontalSlider_2.value()/self.ratio)/self.dvz2
                self.i_akhirz2 = i_mulai + t

            if int(a) == 6:
                self.OnRampzs=1
                
                self.vs_end = b

                if(self.horizontalSlider_3.value()/self.ratio > self.vs_end):
                    self.dvzs= -1*dvz
                else:
                    self.dvzs= dvz
                
                t = (self.vs_end - self.horizontalSlider_3.value()/self.ratio)/self.dvzs
                self.i_akhirzs = i_mulai + t

    def stop_ramp(self,a):
        if self.DoubleSlider==1 and (int(a)==2 or int(a)==4):
            self.OnRampz1=0
            self.OnRampz2=0
        else:
            if int(a)==2:
                self.OnRampz1=0
            if int(a)==4:
                self.OnRampz2=0
            if int(a)==6:
                self.OnRampzs=0              
  
    def update_plot_data(self):
        def fdYdt(t,Y,t0,z10,z20,zs0,dvz1,dvz2,dvzs):
            
            Q = Y[0]
            C = Y[1:7]
            Tr = Y[7]
            print("t =",t,"   t0=",t0)
            #Parameter Z1, Z2, Zs
            
            z1 = z10+dvz1*(t-t0)
            z2 = z20+dvz2*(t-t0)
            zs = zs0+dvzs*(t-t0)

            rho=self.rhoin + React().reactivity_func(Tr, z1, z2, 0)
            total_precursor= sum(Const.lambda_groups * C) + par_s().fs(zs)
            
            dQdt=zeros(1)
            dTrdt=zeros(1)
        

            dQdt[0] = (Q/Const.lp) * ((rho - sum(Const.beta_groups))/(1-rho)) + \
                      ((Param.e * Param.k * Param.v_fuel)/(Const.lp * Param.eta * Param.eps * (1-rho)) * total_precursor)
            dCdt = ((Const.beta_groups * Param.eta * Param.eps * Q)/(Param.e * Param.k * Param.v_fuel)) - (Const.lambda_groups * C)
            dTrdt[0]= (Q - (Param.u_reactor * (Tr - Param.t_msp))) / (Param.m_reactor * Param.cpr)

            #print("param_s= ",par_s().fs(zs),"  dQdt= ",dQdt[0],"    rho =", rho)
            
            dYdt=zeros(8)
            dYdt[0]=dQdt
            dYdt[1:7]=dCdt
            dYdt[7]=dTrdt

            return  dYdt
        
        if self.OnRampz1 == 1:
            self.horizontalSlider.setValue(int(self.horizontalSlider.value()+self.dvz1*self.ratio))
            if self.i_akhirz1 < self.i:
                self.horizontalSlider.setValue(self.v1_end*self.ratio)
                self.OnRampz1=0
                self.dvz1=0
        if self.OnRampz2 == 1:
            self.horizontalSlider_2.setValue(int(self.horizontalSlider_2.value()+self.dvz2*self.ratio))
            if self.i_akhirz2 < self.i:
                self.horizontalSlider_2.setValue(self.v2_end*self.ratio)
                self.OnRampz2=0
                self.dvz2=0
        if self.OnRampzs == 1:
            self.horizontalSlider_3.setValue(int(self.horizontalSlider_3.value()+self.dvzs*self.ratio))
            if self.i_akhirzs < self.i:
                self.horizontalSlider_3.setValue(self.vs_end*self.ratio)
                self.OnRampzs=0
                self.dvzs=0
        
        sol=solve_ivp(fdYdt,[self.i-1,self.i],self.Y0,method='LSODA',t_eval=linspace(self.i-1,self.i,5),\
            args=(self.i-1,self.z1,self.z2,self.zs,self.dvz1,self.dvz2,self.dvzs))
        self.rho=self.rhoin + React().reactivity_func(sol.y[7,:],array([self.z1+self.dvz1*(i-sol.t[0]) for i in sol.t]),array([self.z2+self.dvz2*(i-sol.t[0]) for i in sol.t]), 0)
        self.i+=1
        
        #append graph
        self.x=append(self.x,sol.t[1:-1])
        self.y=append(self.y,sol.y[0,1:-1])   
        self.y_2=append(self.y_2,sol.y[7,1:-1])
        self.y_3=append(self.y_3,self.rho[1:-1])

        
        self.Y0=sol.y[:,-1]
        self.data_line.setData(self.x, self.y)  # Update the data.
        self.data_line_2.setData(self.x, self.y_2)  # Update the data.
        self.data_line_3.setData(self.x, self.y_3)  # Update the data.
        
        self.label_nilai_Q.setText("Q  = {:.2f} W".format(self.y[-1]))
        self.label_nilai_T.setText("Tr = {:.2f} C".format(self.y_2[-1]))
        self.label_nilai_R.setText("Reactivity = {:.2f}".format(self.y_3[-1]))
        self.label_nilai_t.setText("Time = {:.2f} sekon".format(self.x[-1]))
        #if self.i % 50 == 0:
        #    print(self.i/(time() - self.timer_on))
    
    def reset(self):
        self.x = [0]  # 
        self.y = [self.Q]  # 
        self.y_2 = [self.T]  #
        self.y_3 = [self.rhoin]  #
        #re-initiate
        #initiate
        self.rho = Param.rho
        self.Q = Param.power #Inisialisasi Daya Awal (kW)
        self.T = Param.t_reactor #Suhu Reaktor (K) INISIALISASI
        self.h = Const.t_interval
        self.rhoin = Param.rho
        self.Y0[0] = self.Q # Nilai daya pada kolom ke-1 q
        self.Y0[1:7]=Const.precursor_groups
        self.Y0[7] = self.T # Nilai suhu inisial reaktor """
        self.i = 1
        self.widget.setTransform(QTransform())
        self.widget_plot_2.setTransform(QTransform())
        self.widget_plot_3.setTransform(QTransform())

        self.rampspeed.setReadOnly(False)
        self.rampspeed.setStyleSheet("background-color : white")
        self.rampspeed.setText(str(ramp_speed_innate_value))

        self.horizontalSlider.setValue(z1z2_initiate_value*self.ratio)
        self.horizontalSlider_2.setValue(z1z2_initiate_value*self.ratio)
        self.horizontalSlider_3.setValue(zs_initiate_value)

        self.label_slider_1.setText(self.label_slider_1.text())# 
        self.label_slider_2.setText(self.label_slider_2.text())# 
        self.label_slider_3.setText(self.label_slider_3.text())

        self.OnRampz1 = 0
        self.OnRampz2 = 0
        self.OnRampzs = 0
        self.dvz1 = 0
        self.dvz2 = 0
        self.dvzs = 0
        self.data_line.setData(self.x, self.y)  # Update the data.
        self.data_line_2.setData(self.x, self.y_2)  # Update the data.
        self.data_line_3.setData(self.x, self.y_3)  # Update the data.
        
        self.label_nilai_Q.setText("Q  = {:.2f} W".format(0))
        self.label_nilai_T.setText("Tr = {:.2f} C".format(0))
        self.label_nilai_R.setText("Reactivity = {:.2f}".format(0))
        self.label_nilai_t.setText("Time = {:.2f} sekon".format(0))

    # Plotting Widgets
        self.plotheight=150
        self.plotwidth= 800
        self.indentforlabel=50
        #Q1
        self.widget = PlotWidget(self.SimulasiPage)
        self.widget.setGeometry(QRect(500, 10,  self.plotwidth, self.plotheight))
        self.widget.setObjectName("widget")
        
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        
        self.label_nilai_Q = QLabel(self.SimulasiPage)
        self.label_nilai_Q.setGeometry(QRect(500+self.indentforlabel, 5+self.plotheight*1 , 140, 20))
        self.label_nilai_Q.setFont(font)
        self.label_nilai_Q.setObjectName("label_nilai_Q")
        self.label_nilai_Q.setText("Q  = {:.2f} W".format(0))
        self.label_nilai_Q.setStyleSheet("color: red;")
        
        self.pushButton_maximize_Q = QPushButton(self.SimulasiPage)
        self.pushButton_maximize_Q.setObjectName("pushButton_maximize_Q")
        self.pushButton_maximize_Q.setGeometry(QRect(1220, 5+self.plotheight*1 , 75, 20))
        self.pushButton_maximize_Q.clicked.connect(lambda x:self.enlarge_plot(self.widget,self.label_nilai_Q,self.pushButton_maximize_Q))
        self.pushButton_maximize_Q.setText("Maximize")

        self.pushButton_mode_Q = QPushButton(self.SimulasiPage)
        self.pushButton_mode_Q.setObjectName("pushButton_mode_Q")
        self.pushButton_mode_Q.setGeometry(QRect(1100, 5+self.plotheight*1 , 100, 20))
        self.pushButton_mode_Q.clicked.connect(lambda: self.plotQ_mode())
        self.pushButton_mode_Q.setText("Logaritmic Mode")


        #T
        self.widget_plot_2 = PlotWidget(self.SimulasiPage)
        self.widget_plot_2.setGeometry(QRect(500, 40+self.plotheight*1,  self.plotwidth, self.plotheight))
        
        self.label_nilai_T = QLabel(self.SimulasiPage)
        self.label_nilai_T.setGeometry(QRect(500+self.indentforlabel, 45+self.plotheight*2 , 140, 20))
        self.label_nilai_T.setFont(font)
        self.label_nilai_T.setText("Tr = {:.2f} C".format(0))
        self.label_nilai_T.setStyleSheet("color: blue;")
        
        self.pushButton_maximize_T = QPushButton(self.SimulasiPage)
        self.pushButton_maximize_T.setObjectName("pushButton_maximize_T")
        self.pushButton_maximize_T.setGeometry(QRect(1220, 45+self.plotheight*2 , 75, 20))
        self.pushButton_maximize_T.clicked.connect(lambda x:self.enlarge_plot(self.widget_plot_2,self.label_nilai_T,self.pushButton_maximize_T))
        self.pushButton_maximize_T.setText("Maximize")
        
        #rho
        self.widget_plot_3 = PlotWidget(self.SimulasiPage)
        self.widget_plot_3.setGeometry(QRect(500, 80+self.plotheight*2,  self.plotwidth, self.plotheight))
        self.widget_plot_3.setObjectName("widget_plot_3")
        
        self.label_nilai_R = QLabel(self.SimulasiPage)
        self.label_nilai_R.setGeometry(QRect(500+self.indentforlabel, 85+self.plotheight*3 , 140, 20))
        self.label_nilai_R.setFont(font)
        self.label_nilai_R.setObjectName("label_nilai_R")
        self.label_nilai_R.setText("Reactivity = {:.2f}".format(0))
        self.label_nilai_R.setStyleSheet("color: black;")
        
        self.pushButton_maximize_R = QPushButton(self.SimulasiPage)
        self.pushButton_maximize_R.setObjectName("pushButton_maximize_Q")
        self.pushButton_maximize_R.setGeometry(QRect(1220, 85+self.plotheight*3 , 75, 20))
        self.pushButton_maximize_R.clicked.connect(lambda x:self.enlarge_plot(self.widget_plot_3,self.label_nilai_R,self.pushButton_maximize_R))
        self.pushButton_maximize_R.setText("Maximize")
        
        #time
        self.label_nilai_t = QLabel(self.SimulasiPage)
        self.label_nilai_t.setGeometry(QRect(800+self.indentforlabel, 85+self.plotheight*3 , 140, 20))
        self.label_nilai_t.setFont(font)
        self.label_nilai_t.setObjectName("label_nilai_t")
        self.label_nilai_t.setText("Time = {:.2f} sekon".format(0))
        self.label_nilai_t.setStyleSheet("color: black;")
        
        #draw plot
        self.x = [0]  # 
        self.y = [self.Q]  # 
        self.y_2 = [self.T]  #
        self.y_3 = [self.rhoin] 

        self.widget.setBackground('w')
        self.widget.plotItem.setLabel("left",text="Daya(W)")
        self.widget.plotItem.setLabel("bottom",text="Time(s)")
        self.widget.plotItem.showGrid(True,True)

        self.widget_plot_2.setBackground('w')
        self.widget_plot_2.plotItem.setLabel('left', text="Suhu(K)")
        self.widget_plot_2.plotItem.setLabel("bottom",text="Time(s)")
        self.widget_plot_2.plotItem.showGrid(True,True)

        self.widget_plot_3.setBackground('w')
        self.widget_plot_3.plotItem.setLabel("left",text="rho")
        self.widget_plot_3.plotItem.setLabel('bottom', "Time(s)")
        self.widget_plot_3.plotItem.showGrid(True,True)

        pen1 = mkPen(color=(255, 0, 0),width=1)
        pen2 = mkPen(color=(0, 0, 255),width=1)
        pen3 = mkPen(color=(0, 0, 0),width=1) 
        
        self.data_line =  self.widget.plot(self.x, self.y, pen=pen1)
        self.data_line_2 =  self.widget_plot_2.plot(self.x, self.y_2, pen=pen2)
        self.data_line_3 =  self.widget_plot_3.plot(self.x, self.y_3, pen=pen3)

    def plotQ_mode(self):
        self.Q_mode = not self.Q_mode  #Toggle Variable between 0 and 1
        self.widget.plotItem.setLogMode(False,self.Q_mode)

        if self.Q_mode ==0:
            self.pushButton_mode_Q.setText("Logaritmic Mode")
        else:
            self.pushButton_mode_Q.setText("Linear Mode")


    def enlarge_plot(self,a,b,c):
        if self.maximize_plot == None:
            a.move(500, 10)
            a.resize(self.plotwidth,520)
            a.raise_()
            b.move(500+self.indentforlabel, 85+self.plotheight*3)
            b.raise_()
            c.move(1220, 85+self.plotheight*3)
            c.setText("Minimize")
            c.raise_()
            self.maximize_plot=a
            if a !=self.widget_plot_3 :
                self.label_nilai_R.setHidden(True)
            if a == self.widget:
                self.pushButton_mode_Q.move(1100, 85+self.plotheight*3 )

        elif self.maximize_plot==self.widget :
            a.move(500, 10)
            a.resize(  self.plotwidth,self.plotheight)
            a.raise_()
            b.move(500+self.indentforlabel, 5+self.plotheight*1)
            b.raise_()
            c.move(1220, 5+self.plotheight*1)
            c.setText("Maximize")
            self.pushButton_mode_Q.move(1100, 5+self.plotheight*1)
            c.raise_()
            self.pushButton_mode_Q.raise_()
            self.label_nilai_R.setHidden(False)
            self.maximize_plot=None
        elif self.maximize_plot==self.widget_plot_2 :
            a.move(500, 40+self.plotheight)
            a.resize(self.plotwidth,self.plotheight)
            a.raise_()
            b.move(500+self.indentforlabel, 45+self.plotheight*2)
            b.raise_()
            c.move(1220, 45+self.plotheight*2)
            c.setText("Maximize")
            c.raise_()
            self.label_nilai_R.setHidden(False)
            self.maximize_plot=None
        elif self.maximize_plot==self.widget_plot_3 :
            a.move(500, 80+self.plotheight*2)
            a.resize(self.plotwidth,self.plotheight)
            a.raise_()
            b.raise_()
            c.setText("Maximize")
            c.raise_()
            self.maximize_plot=None

    def Kembali(self):
        self.stackedWidget.setCurrentIndex(1)

    def Simulasi(self):
        self.stackedWidget.setCurrentIndex(2)

    def Instruksi(self):
        self.stackedWidget.setCurrentIndex(0)

    def Tentang(self):
        self.stackedWidget.setCurrentIndex(3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulasi Dinamika Reaktor Titik"))
        self.KembaliButton_3.setText(_translate("MainWindow", "Kembali"))
        self.KembaliButton_3.clicked.connect(self.Kembali)
        self.SimulasiLabel_3.setText(_translate("MainWindow", "Instruksi Penggunaan"))
        self.label_24.setText(_translate("MainWindow", "A. Mulai dan Berhenti"))
        self.label_25.setText(_translate("MainWindow", "1. Untuk menjalankan simulasi, tekan tombol “Start”. "))
        self.label_26.setText(_translate("MainWindow", "2. Untuk memberhentikan simulasi, tekan tombol “Stop”."))
        self.label_27.setText(_translate("MainWindow", "3. Untuk mengatur ulang simulasi, tekan tombol “Reset”. Tombol “Reset” hanya bisa digunakan ketika simulasi dihentikan"))
        self.label_28.setText(_translate("MainWindow", "4. Jika ingin memulai kembali simulasi dengan kondisi saat ini, tekan tombol “Start”.\n"
""))
        self.label_29.setText(_translate("MainWindow", "B. Pengendalian"))
        self.label_30.setText(_translate("MainWindow", "1. Z1 adalah kelompok 1 reflektor samping."))
        self.label_31.setText(_translate("MainWindow", "2. Z2 adalah kelompok 2 reflektor samping."))
        self.label_32.setText(_translate("MainWindow", "3. Zs adalah sumber neutron."))
        self.label_33.setText(_translate("MainWindow", "4. Posisi Z1, Z2, dan Zs dapat diatur sebelum menjalankan simulasi. Disarankan posisi awal Z1, Z2, dan Zs untuk memulai simulasi berada pada Fully Down (FD).\n"
"    Posisi FD masing-masing adalah -100, -100, dan 0."))
        self.label_35.setText(_translate("MainWindow", "5. Pengendalian manual Z1, Z2, dan Zs dapat dilakukan dengan menggerakan slider ketika simulasi sedang berjalan.\n"
""))
        self.label_34.setText(_translate("MainWindow", "C. Sinyal Step"))
        self.label_36.setText(_translate("MainWindow", "1. Sinyal step dilakukan untuk simulasi kecelakaan."))
        self.label_37.setText(_translate("MainWindow", "2. Pengendalian step Z1 dan Z2 adalah perubahan posisi yang dilakukan dengan memasukan sinyal step. Fully Down Step (FD) adalah masukan sinyal step posisi -100.\n"
"    Equlibirum Step (EQ) adalah masukan sinyal step posisi (..masih blm tau..). Fully Up Step (FU) adalah masukan sinyal step posisi 0."))
        self.label_38.setText(_translate("MainWindow", "3. Pengendalian step Zs adalah perubahan posisi yang dilakukan dengan memasukan sinyal step. Fully Down Step (FD) adalah masukan sinyal step posisi 0.\n"
"    Middle Step (MD) adalah masukan sinyal step posisi (..masih blm tau..). Fully Up Step (FU) adalah masukan sinyal step posisi 150.\n"
""))
        self.label_39.setText(_translate("MainWindow", "D. Sinyal Ramp"))
        self.label_40.setText(_translate("MainWindow", "1. Sinyal step dilakukan untuk simulasi kecelakaan.."))
        self.label_41.setText(_translate("MainWindow", "2. Kecepatan sinyal ramp diatur sebelum simulasi dijalankan. Disarankan kecepatan sinyal ramp sebesar 0.3."))
        self.label_42.setText(_translate("MainWindow", "3. Kecepatan sinyal ramp hanya dapat diubah ketika mengatur ulang simulasi dengan menekan tombol “Reset”."))
        self.label_43.setText(_translate("MainWindow", "4. Pengendalian ramp Z1 dan Z2 adalah perubahan posisi yang dilakukan dengan memasukan sinyal ramp. Fully Down Ramp (FD) adalah masukan sinyal step posisi -100.\n"
"    Equlibirum Ramp (EQ) adalah masukan sinyal ramp posisi (..masih blm tau..). Fully Up Ramp (FU) adalah masukan sinyal ramp posisi 0."))
        self.label_44.setText(_translate("MainWindow", "5. Pengendalian ramp Zs adalah perubahan posisi yang dilakukan dengan memasukan sinyal ramp. Fully Down Ramp (FD) adalah masukan sinyal step posisi 0.\n"
"    Middle Ramp (MD) adalah masukan sinyal step posisi (..masih blm tau..). Fully Up Ramp (FU) adalah masukan sinyal ramp posisi 150."))
        self.label_45.setText(_translate("MainWindow", "6. Masukan sinyal ramp dapat dilakukan dengan mengisi posisi pada text box. Nilai masukan untuk Z1 dan Z2 adalah bilangan bulat dalam rentang -100 hingga 0.\n"
"    Sedangkan nilai masukan untuk Zs adalah bilangan bulat dalam rentang 0 hingga 150.\n"
""))
        self.label_47.setText(_translate("MainWindow", "E. Tampilan Hasil"))
        self.label_46.setText(_translate("MainWindow", "1. Nilai parameter yang ditampilkan berupa grafik secara berurutan dari atas hingga bawah adalah grafik daya, grafik suhu, dan grafik reaktivitas."))
        self.label_48.setText(_translate("MainWindow", "2. Untuk melihat grafik lebih detail, perbesaran dan pergeseran dapat dilakukan dengan menggunakan mouse atau touchpad."))
        self.label_49.setText(_translate("MainWindow", "3. Jika ingin kembali ke tampilan awal, tekan tombol A pada pojok kiri bawah grafik."))
        self.label_50.setText(_translate("MainWindow", "4. Untuk memperbesar tampilan grafik, tekan tombol “Maximize” pada pojok kanan bawah grafik dan untuk mengembalikan ke tampilan awal tekan tombol “Minimize”."))
        self.label_51.setText(_translate("MainWindow", "5. Grafik daya terdapat 2 mode, grafik linear dan grafik logaritma. "))
        self.label_13.setText(_translate("MainWindow", "6. Pada setiap grafik, ditampilkan nilai masing-masing sumbu ordinat secara real time."))
        self.label_15.setText(_translate("MainWindow", "7. Tampilan waktu ketiga grafik ditampilkan pada bagian tengah layar."))
        self.label_18.setText(_translate("MainWindow", "Penjabaran mengenai penggunaan aplikasi MHRP atau istilah yang digunakan pada aplikasi akan dijelaskan di bawah ini:"))
        self.label_19.setText(_translate("MainWindow", "Simulasi Dinamika Reaktor Titik"))
        self.label_20.setText(_translate("MainWindow", "TERKAIT DAYA KESETIMBANGAN n SEBAGAI \n"
"FUNGSI POSISI BATANG KENDALI PADA MRHP "))
        self.SimulasiButton.setText(_translate("MainWindow", "Mulai Simulasi"))
        self.TentangButton.setText(_translate("MainWindow", "Tentang"))
        self.InstruksiButton.setText(_translate("MainWindow", "Instruksi"))
        self.KeluarButton.setText(_translate("MainWindow", "Keluar"))
        self.SimulasiLabel.setText(_translate("MainWindow", "Simulasi"))
        self.KembaliButton.setText(_translate("MainWindow", "Kembali"))
        self.KembaliButton.clicked.connect(self.Kembali)
        self.label.setText(_translate("MainWindow", "0"))
        self.Z1StepButton_1.setText(_translate("MainWindow", "-100"))
        self.Z1StepButton_3.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "-100"))
        self.Z1StepButton_2.setText(_translate("MainWindow", "-51"))
        self.Z1Label.setText(_translate("MainWindow", "Z1"))
        self.label_5.setText(_translate("MainWindow", "Step"))
        self.Z1RampButton_1.setText(_translate("MainWindow", "-100"))
        self.Z1RampButton_3.setText(_translate("MainWindow", "0"))
        self.Z1RampButton_2.setText(_translate("MainWindow", "-51"))
        self.RampLabel.setText(_translate("MainWindow", "Ramp"))
        self.label_slider_1.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.Z2StepButton_1.setText(_translate("MainWindow", "-100"))
        self.Z2StepButton_3.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "-100"))
        self.Z2StepButton_2.setText(_translate("MainWindow", "-51"))
        self.Z1Label_2.setText(_translate("MainWindow", "Z2"))
        self.label_6.setText(_translate("MainWindow", "Step"))
        self.Z2RampButton_1.setText(_translate("MainWindow", "-100"))
        self.Z2RampButton_3.setText(_translate("MainWindow", "0"))
        self.Z2RampButton_2.setText(_translate("MainWindow", "-51"))
        self.RampLabel_2.setText(_translate("MainWindow", "Ramp"))
        self.label_slider_2.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "0"))
        self.ZsStepButton_1.setText(_translate("MainWindow", "0"))
        self.ZsStepButton_3.setText(_translate("MainWindow", "150"))
        self.label_8.setText(_translate("MainWindow", "-100"))
        self.ZsStepButton_2.setText(_translate("MainWindow", "75"))
        self.Z1Label_3.setText(_translate("MainWindow", "Zs"))
        self.label_9.setText(_translate("MainWindow", "Step"))
        self.ZsRampButton_1.setText(_translate("MainWindow", "0"))
        self.ZsRampButton_3.setText(_translate("MainWindow", "150"))
        self.ZsRampButton_2.setText(_translate("MainWindow", "75"))
        self.RampLabel_3.setText(_translate("MainWindow", "Ramp"))
        self.label_slider_3.setText(_translate("MainWindow", "0"))
        self.DoubleSlider.setText(_translate("MainWindow", "Double Slider"))
        self.MulaiButton.setText(_translate("MainWindow", "Mulai"))
        self.ResetButton.setText(_translate("MainWindow", "Reset"))
        self.label_21.setText(_translate("MainWindow", "Ramp Speed:"))
        self.SimulasiLabel_2.setText(_translate("MainWindow", "Tentang MRHP"))
        self.KembaliButton_2.setText(_translate("MainWindow", "Kembali"))
        self.label_64.setText(_translate("MainWindow", "Penjelasan bagian:"))
        self.label_54.setText(_translate("MainWindow", "Diagram Sistem Keseluruhan Pembangkit Listrik Reaktor MRHP"))
        self.label_58.setText(_translate("MainWindow", "Untuk melaksanakan penelitian tersebut perlu disusun sebuah simulator kontrol daya reaktor yang dapat menampilkan dan mengendalikan nilai-nilai parameter proses operasi reaktor. Pengendalian reaktor dilakukan dengan cara menggerakan 2 kelompok reflektor (Z1 dan Z2) pada arah sumbu aksial. Nilai-nilai parameter yang ditampilkan dan dikendalikan antara lain: daya reaktor, temperatur reaktor, dan reaktivitas. Simulasi dilakukan pada kondisi tertentu seperti: start-up reaktor, penyisipan reaktivitas undak, dan penyisian reaktivitas tanjak. "))
        self.label_52.setText(_translate("MainWindow", "Micro Reactor Heat Pipe (MRHP) merupakan salah satu klasifikasi reaktor kecil dengan karakter pembangkiran daya dalam rentang 1 MWe hingga 10 MWe. Reaktor MRHP didesain dengan pendingin heat pipes yang membentuk teras reaktor monolitik dengan karakteristik yang solid sehingga mampu mereduksi potensi kerusakan ketika dilakukan pemindahan. Keunggulan MRHP antara lain: umpan balik reaktivitas negatif yang tinggi, densitas daya yang rendah, umur reaktor yang panjang, sistem keselamtan pasid, dan pemindahan panas pasif. Dengan keunggulan tersebut, MRHP cocok untuk diimplementasikan sebagai sumber energi bagi daerah 3T di Indonesia. \n"
""))
        self.label_65.setText(_translate("MainWindow", "1.    Kolam garam cair\n"
"2.    Reflektor grafit atas\n"
"3.    Teras reaktor\n"
"4.    Reflektor grafit bawah\n"
"5.    Reflektor samping (Moving part)\n"
"6.    Silo beton\n"
""))
        self.label_61.setText(_translate("MainWindow", "Teras Reaktor MRHP Dengan Komponen Utama"))
        self.label_56.setText(_translate("MainWindow", "MRHP merupakan salah satu jenis reaktor yang tergolong baru sehingga penelitian untuk pengembangannya perlu dilakukan. Salah satu aspek penelitian adalah pengendalian reaktor yang mampu mencegah terjadiya kecelakaan reaktor nuklir. Pengendalian reaktor dirancang dalam suatu sistem kontrol daya reaktor, di mana temperatur dan daya yang dibangkitkan akan digunakan sebagai umpan balik. Hal ini bertujuan menjaga agar pembangkitan daya reaktor sesuai dengan yang diinginkan dan mempertahankan agar operasi reaktor tidak melebihi batas keselamatan yang telah ditentukan."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
